/* Presentation only. Preserve the original recruitment and fatigue model. */
(()=>{
 const root=document.getElementById('rum-sim');if(!root)return;
 const heading=document.createElement('header');heading.className='rum-heading';heading.innerHTML='<h1>Recrutamento de unidades motoras</h1><p>Do comando neural ao desenvolvimento da força muscular.</p>';root.prepend(heading);
 const board=root.querySelector('.control-board');const settings=document.createElement('details');settings.id='rum-settings';settings.className='settings-disclosure';settings.open=innerWidth>760;const summary=document.createElement('summary');summary.textContent='Parâmetros da tarefa e da resposta muscular';settings.append(summary);board.before(settings);settings.append(board);
 root.querySelector('.quad').id='rum-animation';root.querySelector('.capacity-panel').id='rum-capacities';
 const nav=document.createElement('nav');nav.className='rum-nav';nav.setAttribute('aria-label','Seções do simulador');nav.innerHTML='<a href="#rum-animation">Animação</a><a href="#rum-settings">Parâmetros</a><a href="#force-chart">Gráficos</a>';heading.after(nav);nav.querySelector('[href="#rum-settings"]').addEventListener('click',()=>settings.open=true);
 const legend=document.createElement('div');legend.className='capacity-legend';legend.innerHTML='<span style="--lc:var(--force)"><i></i>Força produzida</span><span style="--lc:var(--central)"><i></i>Capacidade central</span><span style="--lc:var(--periph)"><i></i>Capacidade periférica</span>';root.querySelector('#capacity-chart').before(legend);
 const dialog=document.createElement('dialog');dialog.id='rum-zoom';dialog.setAttribute('aria-labelledby','rum-zoom-title');dialog.innerHTML='<div class="zoom-head"><h2 id="rum-zoom-title"></h2><button type="button" autofocus>Fechar</button></div><div class="zoom-content"></div>';root.append(dialog);let placeholder=null,target=null,opener=null;
 dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{if(placeholder&&target){placeholder.replaceWith(target);placeholder=null;target=null;}opener?.focus();window.dispatchEvent(new Event('resize'));});
 root.querySelectorAll('.panel,.capacity-panel').forEach((panel,i)=>{
  const visual=panel.querySelector('.units-stage,.pool-svg,.chart,.wide-chart');if(!visual)return;let surface=visual;
  if(visual.matches('.chart,.wide-chart')){const scroll=document.createElement('div');scroll.className='chart-scroll';scroll.tabIndex=0;scroll.setAttribute('role','region');scroll.setAttribute('aria-label',panel.querySelector('h3').textContent+' — gráfico com rolagem horizontal');visual.before(scroll);scroll.append(visual);surface=scroll;const note=document.createElement('p');note.className='chart-note';note.textContent='Arraste o gráfico para os lados ou toque em Ampliar.';scroll.after(note);}
  const button=document.createElement('button');button.type='button';button.textContent='Ampliar';button.setAttribute('aria-label','Ampliar '+panel.querySelector('h3').textContent);button.className='panel-zoom';(panel.querySelector('.unit-controls,.modes')||panel.querySelector('.panel-head')).append(button);button.addEventListener('click',()=>{opener=button;target=surface;placeholder=document.createComment('posição original do painel');target.before(placeholder);dialog.querySelector('h2').textContent=panel.querySelector('h3').textContent;dialog.querySelector('.zoom-content').append(target);dialog.showModal();window.dispatchEvent(new Event('resize'));});
 });
 window.dispatchEvent(new Event('resize'));
})();
