const maps = {
  celular: {src:'assets/maps/organizacao-funcional-membranas.webp', title:'Organização funcional e membranas'},
  muscular: {src:'assets/maps/excitabilidade-sistema-muscular.webp', title:'Excitabilidade e sistema muscular'},
  osteoarticular: {src:'assets/maps/sistema-osteoarticular.webp', title:'Sistema osteoarticular'},
  cardiovascular: {src:'assets/maps/cardiovascular-02-circulacao-hemodinamica.webp', title:'Circulação e hemodinâmica'},
  respiratorio: {src:'assets/maps/respiratorio-01-estrutura-mecanica-ventilacao.webp', title:'Estrutura, mecânica e ventilação'},
  integracao: {src:'assets/maps/integracao-cardiorrespiratoria.webp', title:'Integração cardiorrespiratória'}
};

const axes = [
  {id:'celular', label:'01 Celular'},
  {id:'muscular', label:'02 Muscular'},
  {id:'osteoarticular', label:'03 Osteoarticular'},
  {id:'cardiovascular', label:'04 Cardiovascular'},
  {id:'respiratorio', label:'05 Respiratório'},
  {id:'integracao', label:'06 Integração'}
];

const modules = [
  {group:'celular', title:'Potencial de ação na membrana', href:'potencial-acao-membrana.html', goal:'Acompanhar permeabilidade, fluxos de Na⁺ e K⁺ e o potencial.', steps:['Abra o mapa de membranas.','Percorra as 7 etapas sem pular.','Pause na despolarização e nomeie o íon dominante.'], qs:[{q:'Na despolarização rápida, o fluxo principal é:', opts:['K⁺ saindo','Na⁺ entrando','Cl⁻ entrando'], a:1, why:'Pause na despolarização no simulador.'},{q:'O potencial de repouso depende sobretudo de:', opts:['Alta permeabilidade ao K⁺','Bomba de Ca²⁺','Lactato'], a:0, why:'Em repouso a membrana é mais permeável ao K⁺.'},{q:'A Na⁺/K⁺-ATPase serve principalmente para:', opts:['Disparar o pico','Manter os gradientes de Na⁺ e K⁺','Produzir ACh'], a:1, why:'A bomba sustenta gradientes; não é o pico rápido.'},{q:'Erro comum: o PA é um fluxo qualquer. O certo é:', opts:['Há ordem: Na⁺ entra, depois K⁺ sai','Os dois entram juntos','Só o Cl⁻ explica o pico'], a:0, why:'Percorra as 7 etapas sem pular.'},{q:'Este módulo explica o elo de:', opts:['Pressão arterial','Excitabilidade da membrana','Lei de Wolff'], a:1, why:'Sem despolarização não há acoplamento.'}]},
  {group:'celular', title:'Potencial de ação do neurônio', href:'neuronio-interativo.html', goal:'Ver o impulso e a abertura sequencial dos canais.', steps:['Siga o impulso ao longo do axônio.','Marque quando Na⁺ abre e quando K⁺ abre.','Relacione com a placa motora.'], qs:[{q:'Depois do pico, a repolarização ocorre porque:', opts:['Na⁺ continua entrando','K⁺ sai e Na⁺ inativa','ACh aumenta'], a:1, why:'Marque os dois momentos no neurônio.'},{q:'O impulso se propaga porque:', opts:['Um trecho ativa o vizinho','O núcleo empurra o Na⁺','A mitocôndria dispara o PA'], a:0, why:'Siga o ponto de excitação no simulador.'},{q:'A chegada à terminal prepara:', opts:['Liberação na placa motora','Poiseuille','O mapa ósseo'], a:0, why:'Liga o neurônio à contração.'},{q:'Erro comum: Na⁺ e K⁺ abrem juntos. O certo é:', opts:['Abertura sequencial','Não há canais','Só o K⁺ cria o impulso'], a:0, why:'Primeiro Na⁺, depois K⁺.'},{q:'No gesto, este neurônio:', opts:['Leva o comando à unidade motora','Define o VO₂ máximo','Substitui o ATP'], a:0, why:'Intenção vira PA no motoneurônio.'}]},
  {group:'celular', title:'Transporte ativo secundário — SGLT', href:'transporte-ativo-secundario-sglt.html', goal:'Ligar o gradiente de Na⁺ ao cotransporte de glicose.', steps:['Identifique a bomba.','Veja por que a glicose entra sem ATP no SGLT.','Compare com o primário.'], qs:[{q:'O SGLT é secundário porque:', opts:['Usa ATP direto na glicose','Aproveita o gradiente de Na⁺','Não move íons'], a:1, why:'A bomba primária gastou ATP antes.'},{q:'Se a bomba para, o SGLT tende a:', opts:['Acelerar','Perder força com o gradiente','Trocar glicose por K⁺'], a:1, why:'Sem Na⁺ o cotransporte enfraquece.'},{q:'O secundário:', opts:['Gasta ATP no SGLT','Usa um gradiente já criado','É difusão simples'], a:1, why:'Compare os dois mecanismos.'},{q:'Erro comum: glicose entra sozinha. O certo é:', opts:['Na⁺ e glicose andam acoplados','Só osmose pura','K⁺ carrega a glicose'], a:0, why:'Cotransporte.'},{q:'Na aula de EF, isso lembra que:', opts:['Absorção de glicose depende de gradientes','SGLT é contração','O mapa muscular substitui a membrana'], a:0, why:'Energia celular começa na membrana.'}]},
  {group:'muscular', title:'Contração muscular esquelética', href:'contracao-muscular-esqueletica.html', goal:'Do PA ao relaxamento: ACh, Ca²⁺, ATP e sarcômero.', steps:['Relembre o mapa.','Percorra as 7 etapas.','Pare no Ca²⁺ e no ATP.'], qs:[{q:'Sem Ca²⁺ citosólico, a ponte:', opts:['Cicla mais rápido','Não encontra o sítio da actina','Gasta mais ATP'], a:1, why:'A tropomiosina cobre o sítio.'},{q:'O relaxamento exige ATP para:', opts:['Só formar ponte','Recaptar Ca²⁺ e desligar a miosina','Produzir ACh'], a:1, why:'Sem ATP a fibra não relaxa de fato.'},{q:'A ACh atua principalmente na:', opts:['Mitocôndria','Placa motora','Zona H'], a:1, why:'Receptor nicotínico da placa.'},{q:'Erro comum: sem encurtamento não há contração. O certo é:', opts:['Contração exige encurtamento visível','Pode haver tensão sem mudar comprimento','ATP some na isometria'], a:1, why:'Contração é tensão.'},{q:'No agachamento a ordem é:', opts:['Pontes → Ca²⁺ → PA','PA → Ca²⁺ → pontes','ATP → ACh → osso'], a:1, why:'A sequência molecular permanece.'}]},
  {group:'muscular', title:'Acoplamento excitação–contração', href:'acoplamento-excitacao-contracao.html', goal:'Do impulso à liberação de Ca²⁺.', steps:['Siga placa → túbulos T → retículo → sarcômero.','Nomeie ACh e RyR.','Pergunte o que quebra o acoplamento na fadiga.'], qs:[{q:'O PA penetra a fibra pelos:', opts:['Núcleos','Túbulos T','Mitocôndrias'], a:1, why:'Levam a despolarização às cisternas.'},{q:'O Ca²⁺ das pontes sai sobretudo do:', opts:['Sangue','Retículo sarcoplasmático','Rim'], a:1, why:'RyR libera Ca²⁺ para o citosol.'},{q:'Sem ACh na fenda:', opts:['O sarcômero encurta sozinho','A placa não despolariza','O ATP aumenta'], a:1, why:'Sem placa não há PA na fibra.'},{q:'Na fadiga, um ponto frágil é:', opts:['A cor do músculo','Recaptação e disponibilidade de Ca²⁺','Lei de Wolff'], a:1, why:'O sinal pode chegar e o acoplamento falhar.'},{q:'A melhor manobra é:', opts:['Mudar três variáveis','Seguir um caminho e nomear cada estrutura','Pular para Hill'], a:1, why:'Acoplamento é sequência.'}]},
  {group:'muscular', title:'Contração muscular e sarcômero', href:'contracao-muscular-sarcomero.html', goal:'Ciclo das pontes, ATP e zona H.', steps:['Observe actina, miosina e zona H.','Acompanhe um ciclo.','Relacione encurtamento com deslizamento.'], qs:[{q:'Na contração, os filamentos:', opts:['Encolhem','Deslizam e a zona H reduz','Somem'], a:1, why:'Sobreposição aumenta.'},{q:'O ATP no ciclo serve para:', opts:['Colar a miosina para sempre','Desligar a miosina e recarregar a cabeça','Produzir ACh'], a:1, why:'Sem ATP a cabeça não solta.'},{q:'Erro comum: a actina diminui. O correto é:', opts:['Os filamentos deslizam','A actina evapora','Só a miosina some'], a:0, why:'Teoria do deslizamento.'},{q:'Sarcômero muito alongado: a força tende a:', opts:['Subir sempre','Cair por menor sobreposição','Ficar igual'], a:1, why:'Poucas pontes possíveis.'},{q:'No agachamento, isto explica:', opts:['Por que a força muda com o ângulo','A cor da barra','A saturação da Hb'], a:0, why:'O comprimento muda com a posição.'}]},
  {group:'muscular', title:'Contrações musculares interativas', href:'contracoes-musculares-interativas.html', goal:'Comparar estática, dinâmica e isocinética.', steps:['Defina se há mudança de comprimento.','Compare carga e movimento.','Traga um gesto da aula.'], qs:[{q:'Na isométrica há:', opts:['Tensão sem mudança de comprimento','Ausência de tensão','Só encurtamento'], a:0, why:'A prancha é o exemplo.'},{q:'Na concêntrica o músculo:', opts:['Alonga sob tensão','Encurta com tensão','Fica sem ATP'], a:1, why:'Subida do agachamento.'},{q:'Na excêntrica o músculo:', opts:['Não produz força','Alonga produzindo tensão','Só existe no cardíaco'], a:1, why:'Descida controlada.'},{q:'Isocinética se caracteriza por:', opts:['Velocidade angular controlada','Torque zero','Ser igual à isometria'], a:0, why:'O equipamento impõe a velocidade.'},{q:'Erro comum: isometria não treina. O certo é:', opts:['Há tensão mesmo sem deslocar a carga','Não há unidades motoras','O mapa some'], a:0, why:'Movimento visível não define contração.'}]},
  {group:'muscular', title:'Hill × Isocinético', href:'modelos-hill-isocinetico.html', goal:'Força, velocidade, torque e potência.', steps:['Comece lento.','Aumente só a velocidade.','Ache a potência máxima.'], qs:[{q:'Se a velocidade de encurtamento sobe:', opts:['A força sobe','A força cai','A força fica igual'], a:1, why:'Relação inversa força–velocidade.'},{q:'A potência máxima costuma ocorrer:', opts:['Na força máxima e velocidade zero','Em combinação intermediária','Só com carga nula'], a:1, why:'Potência = força × velocidade.'},{q:'Carga próxima da isometria implica:', opts:['Velocidade alta','Velocidade próxima de zero','VO₂ nulo'], a:1, why:'Quase não há encurtamento.'},{q:'Erro comum: mais força é sempre mais potência. O certo é:', opts:['Potência também depende da velocidade','Potência é só a barra','Hill não vale no esporte'], a:0, why:'Agachamento lento pode ter muita força e pouca potência.'},{q:'No arremesso, frente ao agachamento lento, você espera:', opts:['Menor velocidade','Maior velocidade e menor força instantânea','Sem unidades motoras'], a:1, why:'Gesto balístico vive a parte rápida da curva.'}]},
  {group:'muscular', title:'Da intenção ao movimento', href:'da-intencao-ao-movimento.html', goal:'Drive, vias, recrutamento e frequência.', steps:['Não pule do córtex ao sarcômero.','Separe recrutamento e taxa.','Abra a leitura se quiser.'], qs:[{q:'Recrutamento e frequência:', opts:['São a mesma coisa','São dois modos de graduar força','Só existem no cardíaco'], a:1, why:'Mais unidades ou mais disparos.'},{q:'Erro comum: ir da intenção ao sarcômero. Falta:', opts:['Nada','Vias, motoneurônio e placa','Só o mapa ósseo'], a:1, why:'Percorra a viagem do módulo.'},{q:'Unidades menores são recrutadas:', opts:['Por último','Primeiro','Nunca'], a:1, why:'Princípio do tamanho.'},{q:'Drive e atenção importam porque:', opts:['Não alteram o comando','Modulam o comando às unidades','Substituem o ATP'], a:1, why:'O módulo começa aí.'},{q:'Ao ensinar um gesto novo:', opts:['Só o sarcômero basta','Atenção e via motora entram antes da técnica isolada','Hill anula o SN'], a:1, why:'Técnica não nasce no filamento.'}]},
  {group:'osteoarticular', title:'Homeostase do cálcio', href:'homeostase-do-calcio.html', goal:'PTH, vitamina D, calcitonina, intestino, rim e osso.', steps:['Abra o mapa.','Altere um hormônio de cada vez.','Explique o plasma.'], qs:[{q:'Queda do Ca²⁺ plasmático tende a elevar:', opts:['Calcitonina','PTH','Insulina'], a:1, why:'Mude só o PTH e veja o plasma.'},{q:'A vitamina D favorece:', opts:['Queda da absorção intestinal','Absorção intestinal de Ca²⁺','O fim do PTH'], a:1, why:'Altere um eixo de cada vez.'},{q:'A calcitonina tende a:', opts:['Elevar o Ca²⁺ plasmático','Reduzir o Ca²⁺ plasmático','Substituir o rim'], a:1, why:'Contraponto do PTH.'},{q:'Erro comum: osso não participa da calcemia. O certo é:', opts:['O osso é reservatório regulado','Só o intestino conta','O Ca²⁺ ósseo não se move'], a:0, why:'Siga osso, rim e intestino.'},{q:'No treino, o Ca²⁺ do plasma:', opts:['Não se relaciona com músculo ou osso','É regulado o tempo todo','Some na contração'], a:1, why:'Plasma ≠ Ca²⁺ da fibra.'}]},
  {group:'osteoarticular', title:'Mecanotransdução e Lei de Wolff', href:'mecanotransducao-lei-de-wolff.html', goal:'Carga mecânica, células ósseas e remodelação.', steps:['Relacione estímulo e adaptação.','Compare carga vs. desuso.','Pense no treino como estímulo ósseo.'], qs:[{q:'A Lei de Wolff descreve:', opts:['Adaptação óssea à carga','Só fratura por estresse','Apenas cartilagem'], a:0, why:'Compare uso e desuso.'},{q:'Quem sente a deformação no osso:', opts:['Osteócitos','Hemácias','Neurônios da placa'], a:0, why:'Rede canalicular.'},{q:'O desuso prolongado tende a:', opts:['Aumentar massa óssea','Reduzir formação e favorecer perda','Eliminar o PTH'], a:1, why:'Sem carga habitual o recado some.'},{q:'Erro comum: força só mexe no músculo. O certo é:', opts:['A carga também é estímulo ósseo','O osso ignora a barra','Só o cardio remodela'], a:0, why:'Tensão e impacto são sinais.'},{q:'A melhor pergunta é:', opts:['Qual carga este osso está sentindo?','Qual a cor do mapa?','Qual a saturação?'], a:0, why:'Comece pelo estímulo.'}]},
  {group:'cardiovascular', title:'Pressão arterial, DC e RPT', href:'hemodinamica-pa-dc-rpt.html', goal:'PA ≈ DC × RPT.', steps:['Comece no repouso.','Mude só o DC, depois só a RPT.','Compare exercício e hemorragia.'], qs:[{q:'A relação central é:', opts:['PA ≈ DC × RPT','PA ≈ VS − FC','PA ≈ só viscosidade'], a:0, why:'Escreva antes dos sliders.'},{q:'DC sobe e RPT cai no exercício: a PAM:', opts:['Copia o DC','Depende do balanço','Depende só da viscosidade'], a:1, why:'Vasodilatação limita a PAM.'},{q:'Na hemorragia, o efeito típico é:', opts:['DC aumenta','Volume e DC caem','Raio infinito'], a:1, why:'Menos retorno, menos pré-carga.'},{q:'Erro comum: DC sobe e PAM copia. O certo é:', opts:['A RPT também entra','A PAM ignora o DC','Só a FC define a PAM'], a:0, why:'Dois fatores.'},{q:'Pressão de pulso sobe quando:', opts:['VS sobe ou a complacência arterial cai','A RPT vira zero','O aluno prende o ar'], a:0, why:'PP = sistólica − diastólica.'}]},
  {group:'cardiovascular', title:'Retorno venoso', href:'retorno-venoso.html', goal:'PAD, volume, tônus e bombas.', steps:['Monte a curva.','Simule ortostatismo.','Ligue retorno e pré-carga.'], qs:[{q:'A bomba muscular:', opts:['Reduz retorno','Favorece o retorno','Elimina o DC'], a:1, why:'Compressão rítmica das veias.'},{q:'PAD alta demais tende a:', opts:['Aumentar o retorno sempre','Diminuir o retorno','Zerar a RPT'], a:1, why:'Cai o gradiente de retorno.'},{q:'No ortostatismo o sangue tende a:', opts:['Subir e aumentar o DC','Acumular nos membros','Ignorar a gravidade'], a:1, why:'Simule a postura.'},{q:'Erro comum: veia não influencia o DC. O certo é:', opts:['Retorno determina a pré-carga','O DC nasce só na aorta','Veia só armazena'], a:0, why:'O que não volta não é ejetado.'},{q:'No exercício, retorno e DC:', opts:['Andam desligados','Sobem juntos','O retorno cai para o DC subir'], a:1, why:'Bombas periféricas sustentam o enchimento.'}]},
  {group:'cardiovascular', title:'Loop cardíaco funcional', href:'loop-cardiaco-funcional.html', goal:'Enchimento, ejeção, volumes e válvulas.', steps:['Nomeie sístole e diástole.','Acompanhe as válvulas.','Relacione VS e DC.'], qs:[{q:'O volume sistólico é:', opts:['VDF − VSF','Só a FC','A RPT'], a:0, why:'Marque os dois volumes.'},{q:'Na sístole o evento central é:', opts:['Enchimento','Ejeção com semilunares abertas','Fechar tudo'], a:1, why:'Acompanhe a queda do volume.'},{q:'Na diástole o ventrículo:', opts:['Ejeta','Enche','Zera a pré-carga'], a:1, why:'Enchimento define o VDF.'},{q:'Erro comum: DC é só FC. O certo é:', opts:['DC = VS × FC','DC = só a mitral','DC = RPT × viscosidade'], a:0, why:'Se o VS cai, a FC não conta sozinha.'},{q:'No exercício o VS sobe quando:', opts:['Enchimento e ejeção melhoram','A válvula some','A PAM ignora o volume'], a:0, why:'Mais retorno, melhor ejeção.'}]},
  {group:'cardiovascular', title:'Lei de Poiseuille', href:'lei-de-poiseuille.html', goal:'Fluxo, ΔP, raio, viscosidade e comprimento.', steps:['Mude só o raio.','Veja o efeito na resistência.','Traga vasodilatação no exercício.'], qs:[{q:'O fluxo é mais sensível a:', opts:['Comprimento','Raio','Temperatura ambiente'], a:1, why:'Raio à quarta potência.'},{q:'Raio pela metade: a resistência:', opts:['Cai pela metade','Sobe desproporcionalmente','Não muda'], a:1, why:'Pequena vasoconstrição pesa.'},{q:'Mais viscosidade tende a:', opts:['Facilitar o fluxo','Aumentar resistência e reduzir fluxo','Eliminar o ΔP'], a:1, why:'Altere só esse parâmetro.'},{q:'Vasodilatação muscular:', opts:['Aumenta o raio e o fluxo local','Fecha o vaso','Anula o DC'], a:0, why:'Ligue à queda da RPT.'},{q:'Erro comum: comprimento manda mais que calibre. O certo é:', opts:['O raio domina','O comprimento anula o raio','Poiseuille não vale'], a:0, why:'Teste os dois sliders.'}]},
  {group:'respiratorio', title:'Mecânica ventilatória', href:'ventilacao-pulmonar.html', goal:'Pressões, volume, complacência, resistência e VE.', steps:['Comece na eupneia.','Altere complacência ou resistência.','Compare com exercício.'], qs:[{q:'Ventilação minuto é:', opts:['VC × frequência','Só PaO₂','Só complacência'], a:0, why:'Escreva antes dos sliders.'},{q:'Se a complacência cai, o esforço para o mesmo volume:', opts:['Fica igual','Aumenta','Zera a resistência'], a:1, why:'Altere só a complacência.'},{q:'Mais resistência das vias aéreas dificulta:', opts:['O fluxo de ar','A cor da Hb','O mapa ósseo'], a:0, why:'Menos fluxo para o mesmo ΔP.'},{q:'Erro comum: ventilar mais é só acelerar. O certo é:', opts:['VC e frequência entram juntos','Só existe FC pulmonar','PaO₂ substitui o VE'], a:0, why:'VE é produto.'},{q:'No exercício a ventilação sobe para:', opts:['Acompanhar a demanda de gás','Eliminar o DC','Parar o retorno'], a:0, why:'Ligue depois com a integração.'}]},
  {group:'respiratorio', title:'Curva de dissociação da hemoglobina', href:'curva-dissociacao-hemoglobina.html', goal:'PO₂, saturação e deslocamentos.', steps:['Marque pulmão e tecido.','Desloque com temperatura.','Não confunda saturação com conteúdo.'], qs:[{q:'No exercício, temperatura e queda de pH:', opts:['Seguram o O₂','Facilitam a cessão aos tecidos','Zeram a saturação arterial'], a:1, why:'Desvio à direita.'},{q:'No pulmão, PO₂ alta faz a Hb:', opts:['Soltar quase todo o O₂','Quase saturar','Ignorar o O₂'], a:1, why:'Parte plana da curva.'},{q:'Erro comum: saturação = conteúdo. O certo é:', opts:['Conteúdo também depende da Hb','Saturação já é o ml de O₂','PO₂ some'], a:0, why:'Menos Hb, menos O₂ mesmo saturado.'},{q:'O 2,3-BPG desloca a curva para:', opts:['Dificultar a cessão','Facilitar a cessão de O₂','Anular a PO₂'], a:1, why:'Outro desvio à direita.'},{q:'A pergunta útil é:', opts:['O músculo está extraindo O₂ desta curva?','Qual a cor do gráfico?','Qual o 1RM?'], a:0, why:'Leve isso ao Fick.'}]},
  {group:'respiratorio', title:'Biofeedback respiratório — smartphone', href:'biofeedback-respiratorio-smartphone.html', goal:'Praticar ciclos com tempos ajustáveis.', steps:['Use no celular.','Comece confortável.','Perceba as fases sem forçar.'], qs:[{q:'Este módulo serve para:', opts:['Diagnosticar asma','Treinar percepção e ritmo','Prescrever FIOs'], a:1, why:'Não é instrumento clínico.'},{q:'O melhor começo é:', opts:['Forçar o ciclo mais longo','Usar tempo confortável e perceber as fases','Prender até tontura'], a:1, why:'Percepção primeiro.'},{q:'Inspiração, pausa e expiração devem ser:', opts:['Nomeadas em sequência','Feitas ao mesmo tempo','Trocadas por apneia competitiva'], a:0, why:'Separe as fases.'},{q:'Erro comum: tratar o app como exame. O certo é:', opts:['Não diagnostica','Substitui espirometria','Mede VO₂ máximo'], a:0, why:'Material de aula.'},{q:'Na disciplina, ajuda a:', opts:['Ligar a mecânica à própria respiração','Memorizar Wolff','Medir PAM'], a:0, why:'Volte ao simulador de ventilação.'}]},
  {group:'integracao', title:'Cardiopulmonar integrado', href:'cardiopulmonar-integrado.html', goal:'Retorno, DC, VO₂, pressões e saturações juntos.', steps:['Compare repouso e exercício.','Mude uma variável.','Conte o O₂ do ar ao músculo.'], qs:[{q:'No exercício o VO₂ sobe porque:', opts:['Só a saturação explode','DC e extração aumentam','O pulmão para'], a:1, why:'Oferta e extração juntos.'},{q:'A história do O₂ vai:', opts:['Do ar ao músculo','Só do ventrículo à barra','Do osso à placa'], a:0, why:'Não comece no meio.'},{q:'Se só o retorno cai:', opts:['Pré-carga e DC tendem a cair','Saturação vira 200%','A RPT some'], a:0, why:'O que não volta não é ejetado.'},{q:'Erro comum: um número isolado. O certo é:', opts:['Ver ventilação, DC, pressões e extração','Ignorar o pulmão','Ignorar o coração'], a:0, why:'Mude uma variável e descreva as outras.'},{q:'Compare repouso e exercício e pergunte:', opts:['O que subiu para entregar mais O₂?','Qual botão é verde?','Qual o PTH?'], a:0, why:'Ponte para o Fick.'}]},
  {group:'integracao', title:'Fick integrado', href:'fick-integrado-cardiorrespiratorio.html', goal:'VO₂ = DC × (CaO₂ − CvO₂).', steps:['Escreva a equação.','Altere DC e depois a diferença a–v.','Veja outros caminhos para o mesmo VO₂.'], qs:[{q:'Se o DC cai e o VO₂ se mantém, a diferença a–v:', opts:['Cai','Sobe','Zera'], a:1, why:'A extração compensa.'},{q:'A equação de Fick é:', opts:['VO₂ = DC × (CaO₂ − CvO₂)','VO₂ = só a FC','VO₂ = RPT × PAM'], a:0, why:'Oferta vezes extração.'},{q:'CaO₂ alto com CvO₂ alto significa:', opts:['Extração pequena','Extração máxima','Ausência de Hb'], a:0, why:'A diferença é que conta.'},{q:'Erro comum: VO₂ só sobe se o DC explode. O certo é:', opts:['Dá para subir também pela extração','DC é o único termo','CvO₂ não existe'], a:0, why:'Dois caminhos.'},{q:'No exercício o músculo recebe mais O₂ por:', opts:['Mais DC e maior diferença a–v','Só vasodilatação cerebral','Só Wolff'], a:0, why:'Oferta e extração.'}]},
  {group:'integracao', title:'Consumo de O₂ e diferença a–vO₂', href:'consumo-o2-debito-cardiaco-diferenca-av.html', goal:'VO₂ absoluto, relativo e oferta vs. extração.', steps:['Separe ml/min e ml·kg⁻¹·min⁻¹.','Compare duas massas.','Ligue com o Fick.'], qs:[{q:'VO₂ relativo serve para:', opts:['Ignorar a massa','Comparar pessoas de massas diferentes','Substituir a FC'], a:1, why:'Normaliza pela massa.'},{q:'VO₂ absoluto é mais útil quando:', opts:['Você quer o consumo total','Quer apagar a massa','Quer a PAM'], a:0, why:'Nomeie a unidade.'},{q:'Diferença a–v maior indica:', opts:['Menos extração','Mais extração pelo tecido','Saturação nula'], a:1, why:'Cai o conteúdo venoso.'},{q:'Erro comum: comparar só pelo absoluto. O certo é:', opts:['A massa altera a leitura; o relativo ajuda','Massa nunca importa','Só a barra conta'], a:0, why:'Use os dois modos.'},{q:'Oferta vs. extração pede que você:', opts:['Separe o que chega e o que o tecido tira','Some PAM com PTH','Troque O₂ por lactato'], a:0, why:'É o Fick em linguagem de aula.'}]}
];

let active = 'muscular';
const axesEl = document.querySelector('#axes');
const cardsEl = document.querySelector('#cards');
const mapModal = document.querySelector('#mapModal');
const mapImage = document.querySelector('#mapImage');
const mapTitle = document.querySelector('#mapTitle');
function openMap(){const map=maps[active];if(!map)return;mapTitle.textContent=map.title;mapImage.src=map.src;mapImage.alt='Mapa mental: '+map.title;mapModal.hidden=false;document.body.classList.add('modal-open');}
function closeMap(){mapModal.hidden=true;document.body.classList.remove('modal-open');mapImage.src='';}
document.querySelector('#closeMap')?.addEventListener('click',closeMap);
if(mapModal) mapModal.addEventListener('click',ev=>{if(ev.target===mapModal)closeMap();});
document.addEventListener('keydown',ev=>{if(mapModal&&ev.key==='Escape'&&!mapModal.hidden)closeMap();});
function renderAxes(){axesEl.innerHTML=axes.map(a=>'<button class="axis" type="button" data-id="'+a.id+'" aria-pressed="'+(a.id===active)+'">'+a.label+'</button>').join('');axesEl.querySelectorAll('.axis').forEach(btn=>btn.addEventListener('click',()=>{active=btn.dataset.id;renderAxes();renderCards();}));}
function renderCards(){const list=modules.filter(m=>m.group===active);cardsEl.innerHTML=list.map((m,i)=>{const qs=m.qs.map((item,qi)=>'<div class="q"><b>'+(qi+1)+'. '+item.q+'</b><div class="opts">'+item.opts.map((opt,oi)=>'<button type="button" data-m="'+i+'" data-q="'+qi+'" data-o="'+oi+'">'+opt+'</button>').join('')+'</div><p class="feedback">'+item.why+'</p></div>').join('');return '<article class="card"><span class="meta">'+m.group+'</span><h2>'+m.title+'</h2><p>'+m.goal+'</p><ol class="steps">'+m.steps.map(s=>'<li>'+s+'</li>').join('')+'</ol><div class="actions"><button class="btn btn-ghost" type="button" data-map>Ver mapa</button><a class="btn btn-primary" href="'+m.href+'">Abrir simulador</a><button class="btn btn-ghost" type="button" data-open>Questões</button></div><div class="panel">'+qs+'</div></article>';}).join('');cardsEl.querySelectorAll('[data-map]').forEach(btn=>btn.addEventListener('click',openMap));cardsEl.querySelectorAll('[data-open]').forEach(btn=>btn.addEventListener('click',()=>{btn.closest('.card').classList.toggle('is-open');}));cardsEl.querySelectorAll('.opts button').forEach(btn=>btn.addEventListener('click',()=>{const m=list[Number(btn.dataset.m)];const item=m.qs[Number(btn.dataset.q)];const ok=Number(btn.dataset.o)===item.a;btn.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('ok','bad'));btn.classList.add(ok?'ok':'bad');const fb=btn.closest('.q').querySelector('.feedback');fb.classList.add('show');fb.textContent=(ok?'Certo. ':'Ainda não. ')+item.why;}));}
if(axesEl&&cardsEl){renderAxes();renderCards();}
