import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {fluxoCanalicular,suave,CORES} from './fisica.js?v=osso-paleta-20261004';
import {quadro,superficie,percurso,maturacaoLocal,maturacaoRegiao} from './animacao.js?v=osso-paleta-20261004';
const V=(x,y,z)=>new THREE.Vector3(x,y,z),TAU=Math.PI*2;
export const NIVEIS=[
 {nome:'O osso',titulo:'Desmonte um órgão vivo',texto:'Separe periósteo, cortical, esponjoso e medula. Setas douradas representam carga e reação; a deformação é ampliada. Reúna as partes para reconhecer o fêmur.'},
 {nome:'As trabéculas',titulo:'Compacto por fora, esponjoso por dentro',texto:'A cortical densa envolve lâminas e hastes interligadas. Os espaços do esponjoso contêm medula e vasos. A arquitetura é irregular, não uma grade; a carga passa pela cortical e pelas trabéculas.'},
 {nome:'O osteócito',titulo:'Do vaso ao ósteon e à célula',texto:'O corte expõe lamelas concêntricas e o canal de Havers, com vasos. O canal de Volkmann comunica a vascularização transversalmente. Lacunas abrigam osteócitos; canalículos comunicam o espaço pericelular. O detalhe ampliado mostra fluido ao redor dos processos, não sangue dentro deles.'},
 {nome:'O osteoclasto',titulo:'Escavar, degradar e transportar',texto:'A zona de selamento isola a superfície. Prótons dissolvem o mineral e enzimas degradam o colágeno. Produtos de degradação entram em vesículas, atravessam a célula e são liberados no interstício, antes da troca com o vaso. A célula trabalha em três regiões sucessivas, sem aparecer formação neste nível. O corte mostra a borda pregueada e a escavação.'},
 {nome:'O osteoblasto',titulo:'Do precursor à matriz mineralizada',texto:'O vaso fornece precursores. O osteoblasto sintetiza e secreta colágeno tipo I, formando osteoide; cálcio e fosfato contribuem para a mineralização extracelular posterior. O detalhe mostra fibrilas entrelaçadas e cristais de hidroxiapatita alinhados. Este nível mostra somente formação e mineralização, em três regiões sucessivas; não começa com osteoclastos.'}
];
export function criar(textura){
 const tex=textura('osso'),lam=textura('lamela'),fib=textura('colageno'),mem=textura('celula');
 const mat=(color,opts={})=>new THREE.MeshPhysicalMaterial({color,roughness:.68,bumpMap:tex,bumpScale:.018,clearcoat:.1,clearcoatRoughness:.7,...opts});
 const M={trabecular:mat('#d2b6a4',{map:tex}),bone:mat('#dfd1c1',{map:tex}),cut:mat('#c6ad99',{map:lam}),lamella:mat('#e6d9ca',{map:lam}),peri:mat('#bd8b82',{map:mem,side:THREE.DoubleSide}),cartilage:mat('#dde1dd',{roughness:.46}),marrow:mat('#8f3d46',{map:mem}),fat:mat('#d9b780'),artery:mat('#bc555c',{roughness:.44}),vein:mat('#827198'),blood:mat('#a93648',{roughness:.42}),cell:mat('#437d70',{map:mem,side:THREE.DoubleSide}),clast:mat('#ce8a8a',{map:mem,side:THREE.DoubleSide}),blast:mat('#8fbaad',{map:mem,side:THREE.DoubleSide}),nucleus:mat('#7c6385',{map:mem}),process:mat('#28594f'),channel:mat('#9c775f',{transparent:true,opacity:.42,depthWrite:false}),fluid:mat('#79d8dc',{emissive:'#51afb3',emissiveIntensity:.24}),proton:mat('#f2bb76',{emissive:'#d08b35',emissiveIntensity:.2}),collagen:mat('#bba079',{map:fib,bumpMap:fib,bumpScale:.009}),crystal:mat('#d8d3c2',{roughness:.60,bumpScale:.001}),mineral:mat(CORES.mineral),force:mat(CORES.carga,{emissive:CORES.carga,emissiveIntensity:.15}),organelle:mat('#a2949e'),vesicle:mat('#dfa7a6',{transparent:true,opacity:.45,depthWrite:false})};
 const sphere=new THREE.SphereGeometry(1,22,16),dot=new THREE.SphereGeometry(1,8,6),plate=(()=>{const shape=new THREE.Shape();for(let i=0;i<6;i++){const a=i*Math.PI/3,x=.042*Math.cos(a)*(1+.1*Math.sin(i*3)),y=.082*Math.sin(a);i?shape.lineTo(x,y):shape.moveTo(x,y);}shape.closePath();const g=new THREE.ExtrudeGeometry(shape,{depth:.012,bevelEnabled:true,bevelSize:.003,bevelThickness:.003,bevelSegments:1});g.translate(0,0,-.006);g.rotateX(Math.PI/2);return g;})();
 const group=()=>{const g=new THREE.Group();g.userData={labels:[],parts:[],flows:[],surfaces:[],cells:[],collagen:[],crystals:[],loads:[]};return g;};
 function label(g,text,p,part=null){g.userData.labels.push({text,pos:V(...p),base:V(...p),part,visible:true});}
 function organic(geo){const p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),s=1+.065*Math.sin(x*6+y*3)*Math.cos(z*5-x)+.014*Math.sin(x*15-z*9);p.setXYZ(i,x*s,y*s,z*s);}geo.computeVertexNormals();return geo;}
 function ell(g,pos,size,m,rough=true){const o=new THREE.Mesh(rough?organic(sphere.clone()):sphere,m);o.position.set(...pos);o.scale.set(...size);g.add(o);return o;}
 function tube(g,points,r,m,end=r,n=20,sides=8){const curve=new THREE.CatmullRomCurve3(points.map(p=>V(...p))),geo=new THREE.TubeGeometry(curve,n,1,sides,false),p=geo.attributes.position;for(let i=0;i<=n;i++){const u=i/n,c=curve.getPointAt(u),rr=r+(end-r)*u;for(let j=0;j<=sides;j++){const k=i*(sides+1)+j;p.setXYZ(k,c.x+(p.getX(k)-c.x)*rr,c.y+(p.getY(k)-c.y)*rr,c.z+(p.getZ(k)-c.z)*rr);}}geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,m);g.add(mesh);return {mesh,curve};}
 function part(g,name,offset,base=[0,0,0]){const p=new THREE.Group();p.name=name;p.userData.flows=g.userData.flows;p.position.set(...base);g.add(p);g.userData.parts.push({g:p,offset:V(...offset),base:V(...base)});return p;}
 function weld(g){const bins=new Map();for(const m of [...g.children]){if(!m.isMesh||m.userData.dynamic)continue;m.updateMatrix();let geo=m.geometry.clone().applyMatrix4(m.matrix);if(!geo.attributes.normal)geo.computeVertexNormals();if(!geo.attributes.uv){const p=geo.attributes.position,u=[];for(let i=0;i<p.count;i++)u.push(p.getX(i),p.getY(i));geo.setAttribute('uv',new THREE.Float32BufferAttribute(u,2));}if(geo.index){const old=geo;geo=geo.toNonIndexed();old.dispose();}if(!bins.has(m.material))bins.set(m.material,[]);bins.get(m.material).push(geo);g.remove(m);}for(const [material,geos]of bins){const geo=mergeGeometries(geos,false);if(geo)g.add(new THREE.Mesh(geo,material));geos.forEach(v=>v.dispose());}}
 function arrow(g,pos,down=false){const a=new THREE.Group();a.position.set(...pos);if(down)a.rotation.z=Math.PI;const rod=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.53,10),M.force);rod.position.y=.26;a.add(rod);const head=new THREE.Mesh(new THREE.ConeGeometry(.12,.23,14),M.force);head.position.y=.64;a.add(head);g.add(a);g.userData.loads.push(a);}
 function forces(g,top,bottom,x,reactionX=x){arrow(g,[x,top+.65,0],true);arrow(g,[reactionX,bottom-.65,0]);label(g,'Carga mecânica',[x,top+.5,.18]);label(g,'Reação',[reactionX,bottom-.55,.18]);}
 function annulus(g,r0,r1,depth,material,start=0,span=TAU){const shape=new THREE.Shape(),n=72;for(let i=0;i<=n;i++){const a=start+span*i/n,x=r1*Math.cos(a),y=r1*Math.sin(a);i?shape.lineTo(x,y):shape.moveTo(x,y);}for(let i=n;i>=0;i--){const a=start+span*i/n;shape.lineTo(r0*Math.cos(a),r0*Math.sin(a));}shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth,steps:1,bevelEnabled:true,bevelSize:.008,bevelThickness:.008,bevelSegments:2});geo.translate(0,0,-depth/2);const m=new THREE.Mesh(geo,material);g.add(m);return m;}
 function vessel(g,points,r=.11,cut=false){const curve=new THREE.CatmullRomCurve3(points.map(p=>V(...p))),geo=new THREE.TubeGeometry(curve,36,r,16,false);if(cut){const ix=[],p=geo.attributes.position;for(let i=0;i<36;i++){const center=curve.getPointAt((i+.5)/36);for(let j=0;j<16;j++){const k=i*17+j,dx=(p.getX(k)+p.getX(k+1))*.5-center.x,dz=(p.getZ(k)+p.getZ(k+1))*.5-center.z;if(dx*.4+dz>r*.28)continue;ix.push(k,k+17,k+1,k+1,k+17,k+18);}}geo.setIndex(ix);}const wall=new THREE.Mesh(geo,cut?M.artery.clone():M.artery);if(cut)wall.material.side=THREE.DoubleSide;g.add(wall);if(cut)for(const u of [0,1]){const p=curve.getPointAt(u),ring=new THREE.Mesh(new THREE.TorusGeometry(r,.017,6,20),M.artery);ring.position.copy(p);ring.quaternion.setFromUnitVectors(V(0,0,1),curve.getTangentAt(u));g.add(ring);}const profile=[];for(let i=0;i<=12;i++){const s=i/12;profile.push(new THREE.Vector2(.063*s,.012+.016*Math.sin(s*Math.PI)));}for(let i=12;i>=0;i--){const s=i/12;profile.push(new THREE.Vector2(.063*s,-.012-.016*Math.sin(s*Math.PI)));}const bgeo=new THREE.LatheGeometry(profile,14);for(let i=0;i<7;i++){const m=new THREE.Mesh(bgeo,M.blood);m.scale.setScalar(r/.11);m.userData.dynamic=true;g.add(m);g.userData.flows.push({m,curve,index:i,type:'blood'});}return curve;}
 function spongy(g,w=2.4,h=2.4,d=1.6,count=54){const nodes=[];for(let i=0;i<count;i++){const a=i*2.399963,r=Math.sqrt((i+.7)/count);nodes.push(V(Math.cos(a)*w*.46*r,Math.sin(a)*h*.47*r,Math.sin(i*1.83)*d*.43));}for(let i=0;i<nodes.length;i++){const a=nodes[i],near=nodes.map((b,j)=>({b,j,d:a.distanceTo(b)})).filter(v=>v.j!==i).sort((a,b)=>a.d-b.d).slice(0,4);for(const v of near){if(v.j<i)continue;const b=v.b,mid=a.clone().lerp(b,.5).add(V(.05*Math.sin(i),.055*Math.cos(v.j),.07*Math.sin(v.j)));tube(g,[a.toArray(),mid.toArray(),b.toArray()],.07+.018*Math.sin(i*3),M.trabecular,.045+.02*Math.cos(v.j),16);}ell(g,a.toArray(),[.095,.075,.085],M.trabecular);}for(let k=0;k<Math.ceil(count/5.4);k++){const shape=new THREE.Shape(),a=k*2.3;for(let j=0;j<=32;j++){const t=j/32*TAU,r=.32+.04*Math.sin(t*3+k);j?shape.lineTo(r*Math.cos(t),r*.7*Math.sin(t)):shape.moveTo(r,0);}const hole=new THREE.Path();hole.absellipse(.045,0,.13,.09,0,TAU,true);shape.holes.push(hole);const geo=new THREE.ExtrudeGeometry(shape,{depth:.045,bevelEnabled:true,bevelSize:.02,bevelThickness:.02,bevelSegments:2});const m=new THREE.Mesh(geo,M.trabecular);m.position.set(.67*Math.cos(a)*w/2.4,.65*Math.sin(a)*h/2.4,.45*Math.sin(k*1.8)*d/1.6);m.rotation.set(k*.71,k*1.34,k*.29);g.add(m);}weld(g);}
 const bone=group(),cortex=part(bone,'Cortical',[-1,0,0]),peri=part(bone,'Periósteo',[4.6,0,0]),marrow=part(bone,'Medula',[3.7,0,0]),epiphysis=part(bone,'Osso esponjoso',[2.1,0,0]),joints=part(bone,'Cartilagem articular',[-3.9,0,0]);
 function cutEpiphysis(pos,size){const m=ell(cortex,pos,size,M.bone),p=m.geometry.attributes.position,ix=m.geometry.index,keep=[];for(let i=0;i<ix.count;i+=3){const a=ix.getX(i),b=ix.getX(i+1),c=ix.getX(i+2);if((p.getZ(a)+p.getZ(b)+p.getZ(c))/3>.35)continue;keep.push(a,b,c);}m.geometry.setIndex(keep);m.material=M.bone.clone();m.material.side=THREE.DoubleSide;}
 function insetSpongy(pos,size){const g=new THREE.Group();spongy(g,2,2,2,22);g.traverse(m=>{if(!m.isMesh)return;const p=m.geometry.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),r=Math.sqrt(x*x+y*y+z*z),k=r>.78?.78/r:1;p.setXYZ(i,x*k*size[0],y*k*size[1],z*k*size[2]);}p.needsUpdate=true;m.geometry.computeVertexNormals();});g.position.set(...pos);epiphysis.add(g);}

 function shaft(g,s,m,start=.74,span=TAU-1.48){const p=[],uv=[],ix=[],ny=80,na=48;for(let i=0;i<=ny;i++){const u=i/ny,y=-2.9+5.3*u,r=(.34+.11*Math.pow(Math.abs(2*u-1),4)+.26*Math.exp(-(((u-.025)/.09)**2))+.1*Math.exp(-(((u-.96)/.13)**2)))*s;for(let j=0;j<=na;j++){const a=start+span*j/na;p.push(.08*Math.sin(u*Math.PI)+r*Math.sin(a),y,.09*Math.sin(u*Math.PI)+r*.84*Math.cos(a));uv.push(j/na,u);}}for(let i=0;i<ny;i++)for(let j=0;j<na;j++){const n=i*(na+1)+j;ix.push(n,n+1,n+na+1,n+1,n+na+2,n+na+1);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(ix);geo.computeVertexNormals();const material=m.clone();material.side=THREE.DoubleSide;g.add(new THREE.Mesh(geo,material));}
 shaft(cortex,1,M.bone);shaft(cortex,.70,M.cut);shaft(peri,1.055,M.peri,0,.82);for(const sign of [-1,1])tube(cortex,[[sign*.25,-2.4,.32],[sign*.23,0,.31],[sign*.27,1.7,.29]],.029,M.cut,.032,32);tube(cortex,[[.06,2.06,.03],[-.29,2.48,.02],[-.76,2.82,.04]],.33,M.bone,.38,36);cutEpiphysis([-1.03,3.03,.04],[.64,.65,.60]);ell(cortex,[.37,2.22,-.07],[.38,.62,.37],M.bone);ell(cortex,[-.28,1.76,-.22],[.18,.29,.19],M.bone);const cap=new THREE.Mesh(new THREE.SphereGeometry(1,32,20,0,TAU,0,Math.PI*.58),M.cartilage);cap.position.set(-1.03,3.03,.04);cap.scale.set(.651,.663,.616);cap.rotation.z=.65;cortex.add(cap);for(const x of [-.36,.36]){cutEpiphysis([x,-3.0,-.04],[.49,.57,.61]);insetSpongy([x,-3.0,-.04],[.49,.57,.61]);ell(cortex,[x,-3.21,.18],[.43,.33,.50],M.cartilage);}ell(marrow,[.06,-.2,-.01],[.22,2.35,.18],M.marrow);vessel(marrow,[[.19,-2.5,.21],[.14,-.4,.25],[.20,1.62,.21]],.031);insetSpongy([-1.03,3.03,.04],[.64,.65,.60]);insetSpongy([.02,1.77,.05],[.27,.56,.22]);label(bone,'Periósteo · envoltório',[.48,.55,.34],peri);label(bone,'Osso compacto · cortical',[-.45,-.7,.27],cortex);label(bone,'Osso esponjoso',[.21,2.04,.56],epiphysis);label(bone,'Medula óssea',[.15,-1.55,.35],marrow);for(const m of [...cortex.children])if(m.material===M.cartilage)joints.add(m);label(bone,'Cartilagem articular',[-1.18,3.47,.42],joints);forces(bone,3.75,-3.7,-1.03,0);[cortex,peri,marrow].forEach(weld);
 const trab=group(),compact=part(trab,'Osso compacto',[-.85,0,0]),network=part(trab,'Osso esponjoso',[.7,0,.2]);annulus(compact,1.35,1.67,1.35,M.bone,.12,TAU-1.25).scale.y=1.05;for(let i=0;i<9;i++){const a=.65+i*.55,p=new THREE.Group();p.position.set(1.52*Math.cos(a),1.52*Math.sin(a),.09);p.scale.setScalar(.16);for(let k=0;k<4;k++)annulus(p,.3+k*.16,.44+k*.16,7.9,k%2?M.cut:M.lamella);compact.add(p);weld(p);}spongy(network,2.65,2.67,1.38);network.traverse(m=>{if(!m.isMesh)return;const p=m.geometry.attributes.position;for(let i=0;i<p.count;i++){let x=p.getX(i),y=p.getY(i),z=p.getZ(i),r=Math.hypot(x,y/1.05);if(r>1.30){x*=1.30/r;y*=1.30/r;}p.setXYZ(i,x,y,Math.max(-.64,Math.min(.64,z)));}p.needsUpdate=true;m.geometry.computeVertexNormals();});const med=part(trab,'Medula e vascularização',[.25,0,.65]);for(let i=0;i<14;i++){const a=i*2.4;ell(med,[Math.sin(a)*1.05,Math.cos(a*1.2)*1.04,Math.sin(a*1.7)*.42],[.15,.12,.14],i%3?M.marrow:M.fat);}vessel(med,[[-1.13,-1.02,0],[-.55,-.6,.14],[.13,.48,0],[.81,1.11,.1]],.068,true);weld(compact);weld(med);label(trab,'Cortical · ósteons',[-1.43,.83,.82],compact);label(trab,'Lâminas e hastes',[.45,.83,.67],network);label(trab,'Medula entre trabéculas',[-.37,-.74,.60],med);label(trab,'Vaso medular',[.25,.46,.26],med);forces(trab,1.9,-1.9,0);
 const cyte=group(),osteon=part(cyte,'Ósteon',[-.22,0,-.3],[-.55,0,0]);for(let i=0;i<8;i++){const r=.30+i*.155;annulus(osteon,r,r+.151,1.62,i%2?M.lamella:M.bone,.45,TAU-1.28);for(let j=0;j<5;j++){const a=.65+j*1.04+.07*Math.sin(i*3+j),p=V((r+.07)*Math.cos(a),(r+.07)*Math.sin(a),.825);ell(osteon,p.toArray(),[.075,.039,.022],M.channel);ell(osteon,p.toArray(),[.055,.021,.023],M.process);for(let b=0;b<3;b++){const d=a+(b-1)*.16,q=V((r-.14)*Math.cos(d),(r-.14)*Math.sin(d),.845);tube(osteon,[p.toArray(),p.clone().lerp(q,.5).add(V(.02,-.018,0)).toArray(),q.toArray()],.010,M.channel,.006,10);}}}for(let i=0;i<12;i++){const a=.7+i*.41,r=.52+(i%6)*.155,p=V(.30*Math.cos(a),.30*Math.sin(a),.85),q=V(r*Math.cos(a),r*Math.sin(a),.85),path=[p.toArray(),p.clone().lerp(q,.5).add(V(.015,.02,0)).toArray(),q.toArray()];tube(osteon,path,.014,M.channel,.008,14);const m=new THREE.Mesh(dot,M.fluid);m.scale.setScalar(.010);m.userData.dynamic=true;osteon.add(m);cyte.userData.flows.push({m,curve:new THREE.CatmullRomCurve3(path.map(v=>V(...v))),index:i+20,type:'fluid',detail:false});}const vascular=part(cyte,'Vasos do canal central',[0,0,.28],[-.55,0,0]);vessel(vascular,[[.04,.07,-1.28],[.04,.07,0],[.04,.07,1.4]],.093,true);tube(vascular,[[-.13,-.08,-1.3],[-.13,-.08,0],[-.13,-.08,1.38]],.060,M.vein,.06,32);vessel(vascular,[[.06,.04,0],[.73,.18,0],[1.5,.12,0]],.053);const detail=part(cyte,'Lacuna ampliada',[.4,.15,.18],[.22,-.45,.97]);detail.scale.setScalar(.65);annulus(detail,.41,.67,.15,M.cut,.15,TAU-1.28).scale.set(1,.69,1);ell(detail,[0,0,.13],[.39,.23,.18],M.cell);ell(detail,[-.055,.02,.235],[.14,.09,.08],M.nucleus);for(let i=0;i<15;i++){const a=i*2.39996,len=.75+.18*Math.sin(i*3),p=V(.27*Math.cos(a),.15*Math.sin(a),.13),q=V(len*Math.cos(a),len*.7*Math.sin(a),.16+.08*Math.sin(i*1.7)),mid=p.clone().lerp(q,.5).add(V(.035*Math.sin(i),.04*Math.cos(i),.01)),path=[p.toArray(),mid.toArray(),q.toArray()];tube(detail,path,.034,M.channel,.023,18);tube(detail,path,.012,M.process,.007,18);const curve=new THREE.CatmullRomCurve3(path.map(v=>V(...v))),m=new THREE.Mesh(dot,M.fluid);m.scale.setScalar(.008);m.userData.dynamic=true;detail.add(m);cyte.userData.flows.push({m,curve,index:i,type:'fluid',detail:true});}label(cyte,'Lamelas concêntricas',[-1.57,.7,.86],osteon);label(cyte,'Canal de Havers · vasos',[-.48,.38,1.38],vascular);label(cyte,'Canal de Volkmann',[.53,.12,.40],vascular);label(cyte,'Lacuna ampliada · osteócito',[.22,-.23,1.21],detail);label(cyte,'Canalículos · fluido pericelular',[.72,-.91,1.22],detail);forces(cyte,1.75,-1.75,-.55);[osteon,detail].forEach(weld);
 function piece(g){const nx=84,nz=38,p=[],uv=[],ix=[];for(let i=0;i<=nx;i++)for(let j=0;j<=nz;j++){const x=-2.16+i/nx*4.32,z=-1.02+j/nz*2.04;p.push(x,0,z*(1+.045*Math.sin(x*7)));uv.push(i/nx,j/nz);}for(let i=0;i<nx;i++)for(let j=0;j<nz;j++){const k=i*(nz+1)+j;ix.push(k,k+1,k+nz+1,k+1,k+nz+2,k+nz+1);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(ix);geo.computeVertexNormals();const surfaceMat=M.bone.clone();surfaceMat.vertexColors=true;geo.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(p.length).fill(1),3));const mesh=new THREE.Mesh(geo,surfaceMat);mesh.userData.dynamic=true;g.add(mesh);g.userData.surfaces.push({mesh,base:p});
  const perimeter=[];for(let i=0;i<=nx;i++)perimeter.push(i*(nz+1));for(let j=1;j<=nz;j++)perimeter.push(nx*(nz+1)+j);for(let i=nx-1;i>=0;i--)perimeter.push(i*(nz+1)+nz);for(let j=nz-1;j>=0;j--)perimeter.push(j);perimeter.push(0);const w=[],wi=[];perimeter.forEach(k=>w.push(p[k*3],0,p[k*3+2],p[k*3],-.84,p[k*3+2]));for(let i=0;i<perimeter.length-1;i++){const k=i*2;wi.push(k,k+1,k+2,k+1,k+3,k+2);}const wallGeo=new THREE.BufferGeometry();wallGeo.setAttribute('position',new THREE.Float32BufferAttribute(w,3));wallGeo.setIndex(wi);const wu=[];for(let i=0;i<w.length;i+=3)wu.push((w[i]+w[i+2])/4,w[i+1]);wallGeo.setAttribute('uv',new THREE.Float32BufferAttribute(wu,2));wallGeo.computeVertexNormals();const material=M.cut.clone();material.side=THREE.DoubleSide;const walls=new THREE.Mesh(wallGeo,material);walls.userData.dynamic=true;g.add(walls);g.userData.surfaces.push({mesh:walls,base:w,wall:true});const bottomShape=new THREE.Shape(perimeter.map(k=>new THREE.Vector2(p[k*3],p[k*3+2]))),bottomGeo=new THREE.ShapeGeometry(bottomShape);bottomGeo.rotateX(Math.PI/2);const bottom=new THREE.Mesh(bottomGeo,material);bottom.position.y=-.84;g.add(bottom);
  const cut=new THREE.Group();for(let k=0;k<24;k++){const x=-2.0+(k%8)*.56+.08*Math.sin(k*5.7),y=-.23-Math.floor(k/8)*.23+.04*Math.sin(k*2.3),z=1.065+.015*Math.sin(k);ell(cut,[x,y,z],[.07,.027,.026],M.channel);for(let j=0;j<4;j++){const a=j*Math.PI/2+.14*Math.sin(k);tube(cut,[[x,y,z],[x+.10*Math.cos(a),y+.06*Math.sin(a),z],[x+.17*Math.cos(a),y+.10*Math.sin(a),z]],.006,M.channel,.003,8);}}for(let i=0;i<8;i++)tube(cut,[[-2.1,-.17-i*.083,1.055],[-.9,-.18-i*.083,1.07],[.6,-.16-i*.083,1.06],[2.12,-.18-i*.083,1.04]],.012,M.collagen,.012,28);weld(cut);g.add(cut);
 }
 function cellBody(g,m,size,clast=false){const geo=organic(new THREE.SphereGeometry(1,48,30)),p=geo.attributes.position,ix=geo.index,keep=[];for(let i=0;i<ix.count;i+=3){const a=ix.getX(i),b=ix.getX(i+1),c=ix.getX(i+2),z=(p.getZ(a)+p.getZ(b)+p.getZ(c))/3,x=(p.getX(a)+p.getX(b)+p.getX(c))/3;if(z>.36&&x>.05)continue;keep.push(a,b,c);}geo.setIndex(keep);const body=new THREE.Mesh(geo,m);body.scale.set(...size);body.position.y=size[1]+.14;g.add(body);
  const edge=[];for(let i=0;i<=30;i++){const u=i/30*Math.PI;edge.push([Math.max(.06,size[0]*Math.cos(u)*.68),size[1]+.14+size[1]*Math.sin(u)*.77,size[2]*.44]);}tube(g,edge,.026,m,.026,30);
  for(let i=0;i<(clast?6:1);i++){const a=i*2.39996;ell(g,[clast?.58*Math.cos(a):-.07,size[1]+.18+.12*Math.sin(a),clast?.32*Math.sin(a):.02],clast?[.20,.17,.16]:[.18,.14,.13],M.nucleus);}
  for(let i=0;i<(clast?8:4);i++){const a=i*2.4,pos=[size[0]*.66*Math.cos(a),size[1]+.2+size[1]*.38*Math.sin(a*1.3),size[2]*.65*Math.sin(a)];const mito=ell(g,pos,[.13,.055,.06],M.organelle);mito.rotation.z=a;for(let j=0;j<3;j++)tube(g,[[pos[0]-.055+j*.04,pos[1]-.04,pos[2]+.035],[pos[0]-.04+j*.04,pos[1]+.035,pos[2]+.04]],.008,M.nucleus,.008,6);}
  if(!clast)for(let k=0;k<5;k++){const path=[];for(let j=0;j<=12;j++)path.push([-.36+j*.06,.22+k*.052+.028*Math.sin(j*.65+k),-.14-.025*Math.sin(j)]);tube(g,path,.022,M.organelle,.015,18);}
  for(let k=0;k<4;k++)tube(g,[[-.04,.46+k*.041,.16],[.20,.48+k*.04,.12],[.33,.43+k*.04,.16]],.018,M.organelle,.009,12);
 }
 function product(g,index,type){const m=new THREE.Group();if(type==='resorption'){const ves=new THREE.Mesh(dot,M.vesicle);ves.scale.setScalar(.065);m.add(ves);m.userData.vesicle=ves;tube(m,[[-.034,-.018,0],[0,.025,0],[.033,-.015,0]],.010,M.collagen,.008,8);ell(m,[.026,0,.026],[.021,.021,.022],M.mineral,false);}else{const nutrient=ell(m,[0,0,0],[.035,.035,.035],type==='precursor'?M.fluid:type==='ions'&&index%2?M.mineral:type==='acid'&&index%3===0?M.nucleus:M.proton,false);if(type==='acid'&&index%3===0){nutrient.scale.set(.058,.040,.048);ell(m,[.028,.019,.01],[.028,.025,.027],M.nucleus,false);}if(type==='precursor'){m.userData.nutrient=nutrient;const fiber=tube(m,[[-.035,-.013,0],[0,.026,0],[.045,-.010,0]],.012,M.collagen,.009,8).mesh;m.userData.procollagen=fiber;}}g.add(m);g.userData.flows.push({m,index,type,curve:new THREE.CatmullRomCurve3([V(0,0,0),V(1,1,0),V(2,0,0)])});}
 function matrixDetail(g){
  const d=part(g,'Ampliação da matriz',[.28,0,.35],[1.12,-.25,1.52]);
  for(let k=0;k<6;k++){
   const bundle=new THREE.Group(),x=(k%3)*.29-.32,y=Math.floor(k/3)*.23;d.add(bundle);
   // Twisted microstrands with closed ends: no hollow pipes or loose bands.
   for(let strand=0;strand<3;strand++){
    const pts=[];for(let j=0;j<=60;j++){const u=j/60,a=u*TAU*2.1+strand*TAU/3;pts.push([x+.042*Math.cos(a)+.024*Math.sin(u*TAU+k),y+.042*Math.sin(a),-.55+u*1.15]);}
    tube(bundle,pts,.032,M.collagen,.028,60,8);for(const [point,r]of [[pts[0],.032],[pts.at(-1),.028]])ell(bundle,point,[r,r,r],M.collagen,false);
   }
   weld(bundle);g.userData.collagen.push({mesh:bundle,index:k/7,detail:true});
   for(let j=0;j<12;j++){const m=new THREE.Mesh(plate,M.crystal),u=j/11;
    // Some platelets lie between the microstrands; others sit between fibrils.
    const internal=j%3===0;m.position.set(x+.024*Math.sin(u*TAU+k)+(internal?.018:(j%2?1:-1)*.074),y+(internal?.005:.025*(j%3-1)),-.48+u*1.0);m.rotation.y=.14*Math.sin(j+k);m.userData.dynamic=true;d.add(m);g.userData.crystals.push({m,index:k/7});
   }
  }
  for(let k=0;k<4;k++){const pts=[];for(let j=0;j<=28;j++){const u=j/28;pts.push([-.42+u*.91,.03+.07*Math.sin(u*TAU+k),-.43+k*.27+.07*Math.sin(u*5)]);}const f=tube(d,pts,.022,M.collagen,.018,28).mesh;f.userData.dynamic=true;g.userData.collagen.push({mesh:f,index:k/6,detail:true});}
  label(g,'Ampliação · colágeno + hidroxiapatita',[1.44,.14,2.00],d);
 }
 const clast=group();piece(clast);const giant=part(clast,'Osteoclasto',[0,1.5,0],[-.7,0,0]);cellBody(giant,M.clast,[1.10,.53,.76],true);for(let i=0;i<44;i++){const a=i*2.4,r=.61*Math.sqrt((i+.5)/44),x=r*Math.cos(a),z=r*Math.sin(a);tube(giant,[[x,.23,z],[x+.027,.08,z+.03],[x-.013,-.02,z+.046]],.042,M.clast,.023,10);}const seal=[];for(let i=0;i<=64;i++){const a=i/64*TAU;seal.push([.93*Math.cos(a),.045,.65*Math.sin(a)]);}const sealMesh=tube(giant,seal,.05,M.clast,.05,64).mesh;sealMesh.userData.dynamic=true;const sealBase=sealMesh.geometry.attributes.position.array.slice();weld(giant);vessel(clast,[[2.42,-.20,-.18],[2.41,.74,-.11],[2.29,1.6,-.15],[2.44,2.4,-.13]],.16,true);for(let i=0;i<18;i++)product(clast,i,'resorption');for(let i=0;i<12;i++)product(clast,i,'acid');label(clast,'Corte · osteoclasto multinucleado',[-.72,1.17,.22],giant);label(clast,'Zona de selamento',[.20,.10,.69],giant);label(clast,'Borda pregueada',[-.60,.04,.68],giant);label(clast,'Prótons e enzimas',[-.89,-.03,.20],giant);label(clast,'Produtos em vesículas',[.24,1.03,.28],giant);label(clast,'Escavação · reabsorção',[-1.20,-.24,.88]);label(clast,'Interstício → troca com o vaso',[2.01,1.83,.17]);
 const blast=group();piece(blast);const cells=part(blast,'Osteoblastos',[0,1.0,0]);for(let i=0;i<4;i++){const c=new THREE.Group();c.position.set(-.825+i*.55,0,-.23);c.scale.setScalar(.70);cells.add(c);cellBody(c,M.blast,[.39,.32,.33]);weld(c);blast.userData.cells.push({g:c,x:c.position.x,z:c.position.z});}vessel(blast,[[-2.61,-.08,-.14],[-2.63,.7,-.10],[-2.55,1.48,-.15],[-2.66,2.15,-.13]],.16,true);for(let i=0;i<14;i++)product(blast,i,'precursor');for(let i=0;i<16;i++)product(blast,i,'ions');for(let i=0;i<24;i++){const x=-1.62+i*.09,pts=[];for(let j=0;j<=16;j++)pts.push([x+.018*Math.sin(j*.8+i),.045,-.58+j*.071]);const f=tube(blast,pts,.013,M.collagen,.010,16).mesh;f.userData.dynamic=true;blast.userData.collagen.push({mesh:f,index:i/25,x,base:f.geometry.attributes.position.array.slice()});}for(let i=0;i<80;i++){const m=new THREE.Mesh(plate,M.crystal),x=-1.52+(i%16)*.14,z=-.52+Math.floor(i/16)*.24;m.position.set(x,.065,z);m.scale.setScalar(.31);m.userData.dynamic=true;blast.add(m);blast.userData.crystals.push({m,index:(i%16)/17,x,z});}matrixDetail(blast);label(blast,'Aminoácidos · síntese e secreção' ,[-2.32,1.76,.06]);label(blast,'Corte · osteoblastos',[-.45,.82,.05],cells);label(blast,'Colágeno secretado · osteoide',[-.86,.04,.74]);label(blast,'Cálcio + fosfato · fora da célula',[.37,-.02,.92]);
 const modelos=[bone,trab,cyte,clast,blast];
 function atualizar(nivel,t,cenario,separacao=0,mostrarCarga=true){
  const a=quadro(t,cenario,nivel===0?separacao:0,mostrarCarga,nivel),g=modelos[nivel];
  g.scale.set(1+(nivel<3?a.deformacao*.3:0),1-(nivel<3?a.deformacao:0),1);
  for(const p of g.userData.parts)p.g.position.copy(p.base).addScaledVector(p.offset,a.separacao);
  for(const arrow of g.userData.loads){arrow.visible=mostrarCarga;arrow.scale.setScalar(.55+1.35*a.forca);}
  for(const l of g.userData.labels){l.pos.copy(l.base);const p=g.userData.parts.find(p=>p.g===l.part);if(p)l.pos.addScaledVector(p.offset,a.separacao);if(/Carga mecânica|Reação/.test(l.text))l.visible=mostrarCarga;if(l.text.startsWith('Ampliação'))l.visible=a.depositada>.001;}
  if(nivel>=3){
   for(const {mesh,base,wall}of g.userData.surfaces){
    const p=mesh.geometry.attributes.position;
    for(let i=0;i<p.count;i++)p.setY(i,wall&&i%2?base[i*3+1]:superficie(base[i*3],base[i*3+2],a));
    p.needsUpdate=true;mesh.geometry.computeVertexNormals();
    if(!wall){const colors=mesh.geometry.attributes.color;for(let i=0;i<p.count;i++){const x=base[i*3],z=base[i*3+2],h=superficie(x,z,a),depth=nivel===3?Math.max(0,-h):0,formed=nivel===4?a.depositada/.22:0;colors.setXYZ(i,1-.35*depth-.04*formed,1-.48*depth+.02*formed,1-.58*depth+.08*formed);}colors.needsUpdate=true;}
   }
   const lift=.20*Math.sin(a.deslocamento*Math.PI);
   if(nivel===3){
    giant.position.set(a.x,superficie(a.x,0,a)+lift,0);
    const positions=sealMesh.geometry.attributes.position;
    for(let i=0;i<positions.count;i++){const x=sealBase[i*3],z=sealBase[i*3+2];positions.setY(i,sealBase[i*3+1]+superficie(x+a.x,z,a)-superficie(a.x,0,a));}
    positions.needsUpdate=true;sealMesh.geometry.computeVertexNormals();
    for(const l of g.userData.labels)if(l.part===giant){l.pos.x=l.base.x+a.x+.7;l.pos.y=l.base.y+giant.position.y;}
   }else{
    cells.position.x=a.x;cells.visible=true;
    for(const c of g.userData.cells)c.g.position.y=superficie(c.x+a.x,c.z,a)+lift;
    for(const l of g.userData.labels)if(l.part===cells){l.pos.x+=a.x;l.pos.y+=superficie(a.x,-.23,a)+lift;}
   }
   for(const f of g.userData.collagen){
    const local=f.detail?maturacaoLocal(.40+.60*t,f.index):maturacaoRegiao(t,f.x);
    f.mesh.visible=local.colageno>.008;
    if(f.detail)f.mesh.scale.y=Math.max(.001,local.colageno);
    else{const p=f.mesh.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,superficie(f.base[i*3],f.base[i*3+2],a)+.022+(f.base[i*3+1]-.045)*local.colageno);p.needsUpdate=true;f.mesh.geometry.computeVertexNormals();}
   }
   for(const c of g.userData.crystals){const local=c.x===undefined?maturacaoLocal(.40+.60*t,c.index):maturacaoRegiao(t,c.x);c.m.visible=local.mineral>.008;c.m.scale.setScalar((c.x===undefined?1:.31)*Math.max(.001,local.mineral));if(c.x!==undefined)c.m.position.y=superficie(c.x,c.z,a)+.06;}
  }
  for(const f of g.userData.flows){
   if(f.type==='blood'){const u=percurso(t,f.index,1,6).u;f.m.position.copy(f.curve.getPointAt(u));f.m.quaternion.setFromUnitVectors(V(0,1,0),f.curve.getTangentAt(u));continue;}
   if(f.type==='fluid'){const u=fluxoCanalicular(t,f.index,a.carga);f.m.position.copy(f.curve.getPointAt(u)).add(V(0,0,f.detail?.024-.009*u:0));continue;}
   const active=f.type==='resorption'||f.type==='acid'?a.transporteReabsorcao:a.transporteFormacao;
   const factor=nivel===3?a.fatorReabsorcao:a.fatorFormacao;
   const {u,escala}=percurso(t,f.index,active,(f.type==='acid'?28:12)*(factor??1));
   f.m.visible=escala>.005;f.m.scale.setScalar(escala);
   if(f.m.userData.vesicle)f.m.userData.vesicle.visible=u>.17&&u<.69;
   if(f.m.userData.nutrient){f.m.userData.nutrient.visible=u<.65;f.m.userData.procollagen.visible=u>=.65;}
   if(!f.m.visible)continue;
   const cx=a.x??-.7,y=superficie(cx,0,a),z=.08*Math.sin(f.index*2.4);
   if(f.type==='resorption')f.curve.points=[V(cx-.16,y-.025,z),V(cx-.15,y+.17,z),V(cx+.03,y+.59,.18),V(cx+.45,y+1.10,.06),V(1.9,1.43,.1),V(2.4,1.58,-.11)];
   if(f.type==='acid')f.curve.points=[V(cx+.35*Math.sin(f.index),y+.25,z),V(cx+.29*Math.sin(f.index),y+.06,z),V(cx+.30*Math.sin(f.index),y+.015,z+.12)];
   if(f.type==='precursor'){const x=cx+g.userData.cells[f.index%4].x,cy=superficie(x,-.23,a);f.curve.points=[V(-2.59,1.4,-.10),V(-1.89,1.07,0),V(x-.08,cy+.32,-.12),V(x+.10,cy+.27,.06),V(x,cy+.04,.30)];}
   if(f.type==='ions'){const x=cx-.36+(f.index%10)*.08;f.curve.points=[V(-2.6,.80,-.12),V(-1.91,.42,.47),V(x-.23,.18,.48),V(x,superficie(x,.38,a)+.045,.38)];}
   f.m.position.copy(f.curve.getPoint(u)).add(V(.018*Math.sin(t*85+f.index),.012*Math.cos(t*69+f.index),.012*Math.sin(t*101+f.index)));
  }
  return a;
 }
 modelos.forEach((_,i)=>atualizar(i,0,'habitual'));
 return {modelos,atualizar,detalhes:[epiphysis,network,detail,giant,blast.userData.parts[1].g]};
}
