const {test,expect}=require('@playwright/test');
const {createTutorServer}=require('../../server/tutor.cjs');
let server,base;
test.beforeAll(async()=>{
  server=createTutorServer({env:{TUTOR_SERVE_SITE:'1'}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  base=`http://127.0.0.1:${server.address().port}`;
});
test.afterAll(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});
async function open(page,course='ef') {
  await page.route('**/api/tutor/status',r=>r.fulfill({json:{enabled:true}}));
  await page.goto(`${base}/tutor-${course}.html`);
  await page.locator('#tutorLauncher').click();
  await page.locator('#tutorAiEnabled').check();
}
async function send(page,text) { await page.locator('#tutorInput').fill(text);await page.locator('.tutor-send').click(); }
for(const course of ['ef','fisio']) test(`${course}: context, history, text safety and clear`,async({page},info)=>{
  const requests=[];
  await page.route('**/api/tutor',async r=>{requests.push(r.request().postDataJSON());await r.fulfill({json:{text:'Explicação de teste: <img src=x onerror=alert(1)>\nQual mudança você prevê?'}});});
  await open(page,course);
  await send(page,'Por que o sódio entra na célula?');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(1);
  expect(requests[0].course).toBe(course);expect(requests[0].module).toBeTruthy();
  await expect(page.locator('.tutor-ai-answer img')).toHaveCount(0);
  await send(page,'Pode explicar com uma analogia?');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(2);
  expect(requests[1].history).toHaveLength(2);
  const form=await page.locator('#tutorForm').boundingBox();
  expect(form.x).toBeGreaterThanOrEqual(0);expect(form.y+form.height).toBeLessThanOrEqual(page.viewportSize().height);
  await page.screenshot({path:info.outputPath('tutor.png')});
  await page.locator('#tutorAiClear').click();
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(0);
  await send(page,'O que faz a bomba de sódio?');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(1);
  expect(requests[2].history).toHaveLength(0);
  await page.reload();await page.locator('#tutorLauncher').click();
  await expect(page.locator('#tutorAiEnabled')).not.toBeChecked();
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(0);
  expect(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k!=='tutorEFPosition'))).toEqual([]);
  await page.locator('.tutor-close').click();
  const card=page.locator('#cards .card').first();
  await card.locator('[data-open]').click();
  await card.locator('.opts button').first().click();
  await page.locator('#tutorLauncher').click();await page.locator('#tutorAiEnabled').check();
  await send(page,'Explique a alternativa que escolhi.');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(1);
  expect(requests[3].question).toEqual({index:0,choice:0});
});
test('quiz remains local, chosen answer accompanies explanation; quota fallback',async({page})=>{
  const requests=[];
  await page.route('**/api/tutor',r=>{requests.push(r.request().postDataJSON());return r.fulfill({status:429,json:{error:'limit'}});});
  await open(page);
  await page.locator('.tutor-close').click();
  await page.locator('#cards .card').first().locator('h2').click();
  await page.locator('#tutorLauncher').click();
  await page.locator('[data-prompt="Teste meu entendimento"]').click();
  await page.locator('.tutor-option').first().click();
  expect(requests).toHaveLength(0);
  await send(page,'Por que errei?');
  await expect(page.locator('#tutorMessages')).toContainText('limite de uso');
  expect(requests[0].question.choice).toBe(0);
  await expect(page.locator('.tutor-send')).toBeEnabled();
});
test('cancel releases input; unavailable key retains original tutor',async({page})=>{
  await page.route('**/api/tutor',async r=>{await new Promise(resolve=>setTimeout(resolve,300));await r.fulfill({json:{text:'Não deve aparecer'}}).catch(()=>{});});
  await open(page);await send(page,'Explique a contração muscular');
  await page.locator('#tutorAiCancel').click();
  await expect(page.locator('#tutorMessages')).toContainText('Resposta cancelada');
  await expect(page.locator('.tutor-send')).toBeEnabled();
  await page.unroute('**/api/tutor/status');
  await page.reload();await page.locator('#tutorLauncher').click();
  await expect(page.locator('#tutorAiEnabled')).toBeDisabled();
  await expect(page.locator('#tutorAiNotice')).toContainText('ainda não disponível');
});
for(const course of ['ef','fisio']) test(`Moodle ${course} iframe: shared API, context, clearing, links and no saved conversation`,async({page})=>{
  const requests=[];
  await page.route('**/api/tutor/status',r=>r.fulfill({json:{enabled:true}}));
  await page.route('**/api/tutor',r=>{requests.push(r.request().postDataJSON());return r.fulfill({json:{text:'Resposta simulada: <b>texto seguro</b>'}});});
  await page.goto(base+'/tutor-ef.html');
  await page.setContent(`<iframe title="Tutor Moodle" src="${base}/tutor-moodle.html${course==='fisio'?'?percurso=fisioterapia':''}" style="border:0;width:100%;height:300px"></iframe>`);
  const frame=page.frameLocator('iframe');
  await expect(frame.locator('.head span')).toContainText(course==='fisio'?'Fisioterapia':'Educação Física');
  await frame.locator('[data-action="simuladores"]').click();
  const actual=await frame.locator('a.link').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href')));
  const {loadCatalog}=require('../../server/catalog.cjs');
  const catalog=loadCatalog(require('node:path').resolve(__dirname,'../..'));
  const extraHref = course === 'ef' ? 'atleta-box.html' : 'fisioterapia/uti-fisiologica.html';
  const expected = catalog[course].map(m=>'https://drmarionascimento.github.io/fisiologia-interativa/'+m.href+(course==='fisio'?'?percurso=fisioterapia':''));
  expected.push('https://drmarionascimento.github.io/fisiologia-interativa/'+extraHref+(course==='fisio'?'?percurso=fisioterapia':'?percurso=educacao-fisica'));
  expect(actual).toEqual(expected);
  await frame.locator('#aiEnabled').check();
  await frame.locator('#input').fill('Por que o sódio entra na célula?');await frame.locator('.send').click();
  await expect(frame.locator('.ai-response')).toContainText('<b>texto seguro</b>');
  await expect(frame.locator('.ai-response b')).toHaveCount(0);
  await frame.locator('#input').fill('Explique com outra analogia');await frame.locator('.send').click();
  await expect(frame.locator('.ai-response')).toHaveCount(2);
  expect(requests[1].history).toHaveLength(2);expect(requests[0].course).toBe(course);
  await frame.locator('[data-action="mapas"]').click();
  await expect(frame.locator('a.link').first()).toHaveAttribute('href',/^https:\/\/drmarionascimento.github.io/);
  expect(requests).toHaveLength(2);
  await frame.locator('#aiClear').click();
  await frame.locator('#input').fill('Explique o potencial de ação');await frame.locator('.send').click();
  await expect(frame.locator('.ai-response')).toHaveCount(2);
  expect(requests[2].history).toHaveLength(0);
  await page.locator('iframe').evaluate(el=>el.contentWindow.location.reload());
  await expect(frame.locator('#aiEnabled')).not.toBeChecked();
  await expect(frame.locator('.ai-response')).toHaveCount(0);
});

for(const course of ['ef','fisio']) test(`${course}: unidades destacam Questões e abrem a RA do sistema ativo`,async({page})=>{
 await page.route('**/api/tutor/status',r=>r.fulfill({json:{enabled:false}}));
 await page.goto(`${base}/tutor-${course}.html`);
 const axes=await page.locator('#axes .axis').count();
 for(let i=0;i<axes;i++) {
  await page.locator('#axes .axis').nth(i).click();
  const cards=page.locator('#cards'),questions=cards.locator('[data-open]'),simulators=cards.getByRole('link',{name:'Abrir simulador',exact:true});
  expect(await questions.count()).toBe(await simulators.count());expect(await questions.count()).toBeGreaterThan(0);
  for(const q of await questions.all())await expect(q).toHaveClass(/btn-primary/);
  for(const sim of await simulators.all())await expect(sim).toHaveClass(/btn-ghost/);
  const styles=await cards.evaluate(el=>({q:getComputedStyle(el.querySelector('[data-open]')).backgroundImage,sim:getComputedStyle([...el.querySelectorAll('a')].find(a=>a.textContent==='Abrir simulador')).backgroundImage}));expect(styles.q).not.toBe(styles.sim);
  await expect(cards.locator('.ra-card')).toHaveCount(1);
  await expect(cards.locator('.ra-card h2')).toHaveText('RA - Realidade Aumentada');
  await expect(cards.locator('.ra-call')).toContainText('viagem de aprendizado incrível');
  const axis=await page.locator('#axes .axis').nth(i).evaluate(b=>b.dataset.id||b.dataset.axis);
  await expect(cards.locator('.ra-card a')).toHaveAttribute('href',`ra/${axis==='cardiovascular'?'retorno-venoso':'pleura'}/?percurso=${course==='fisio'?'fisioterapia':'educacao-fisica'}`);
  const first=questions.first();await first.click();await expect(first.locator('..').locator('..').locator('.panel')).toBeVisible();await first.click();
 }
 const link=page.locator('.ra-card a');await expect(link).toHaveAttribute('target','_blank');
 await page.context().route('**/ra/pleura/app.js*',r=>r.fulfill({body:'',contentType:'text/javascript'}));
 await page.context().route('**/model-viewer.min.js',r=>r.fulfill({body:'',contentType:'text/javascript'}));
 const popupPromise=page.waitForEvent('popup');await link.click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');
 expect(new URL(popup.url()).pathname).toBe('/ra/pleura/');expect(new URL(popup.url()).searchParams.get('percurso')).toBe(course==='fisio'?'fisioterapia':'educacao-fisica');
 await expect(popup.locator('a.small-button[data-voltar-tutor]')).toHaveAttribute('href',`${base}/tutor-${course}.html`);
 expect(await popup.getByRole('link',{name:'Bancadas',exact:true}).count()).toBe(0);
 await expect(link).toHaveAttribute('rel','noopener noreferrer');await popup.close();
 await page.locator('#axes [data-id="cardiovascular"],#axes [data-axis="cardiovascular"]').click();
 await page.context().route('**/ra/retorno-venoso/app.js*',r=>r.fulfill({body:'',contentType:'text/javascript'}));
 const venousPopupPromise=page.waitForEvent('popup');await page.locator('.ra-card a').click();const venous=await venousPopupPromise;await venous.waitForLoadState('domcontentloaded');
 expect(new URL(venous.url()).pathname).toBe('/ra/retorno-venoso/');
 await expect(venous.locator('a.small-button[data-voltar-tutor]')).toHaveAttribute('href',`${base}/tutor-${course}.html`);await venous.close();
});
