const {test,expect}=require('@playwright/test');
const {createTutorServer}=require('../../server/tutor.cjs');
let server,base;
test.beforeAll(async()=>{
  server=createTutorServer({env:{TUTOR_SERVE_SITE:'1'}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  base=`http://127.0.0.1:${server.address().port}`;
});
test.afterAll(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});
async function open(page,course='ef') {
  await page.route('**/api/tutor/status',r=>r.fulfill({json:{enabled:true}}));
  await page.goto(`${base}/tutor-${course}.html`);
  await page.locator('#tutorLauncher').click();
  await page.locator('#tutorAiEnabled').check();
}
async function send(page,text) { await page.locator('#tutorInput').fill(text);await page.locator('.tutor-send').click(); }
for(const course of ['ef','fisio']) test(`${course}: context, history, text safety and clear`,async({page},info)=>{
  const requests=[];
  await page.route('**/api/tutor',async r=>{requests.push(r.request().postDataJSON());await r.fulfill({json:{text:'Explicação de teste: <img src=x onerror=alert(1)>\nQual mudança você prevê?'}});});
  await open(page,course);
  await send(page,'Por que o sódio entra na célula?');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(1);
  expect(requests[0].course).toBe(course);expect(requests[0].module).toBeTruthy();
  await expect(page.locator('.tutor-ai-answer img')).toHaveCount(0);
  await send(page,'Pode explicar com uma analogia?');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(2);
  expect(requests[1].history).toHaveLength(2);
  const form=await page.locator('#tutorForm').boundingBox();
  expect(form.x).toBeGreaterThanOrEqual(0);expect(form.y+form.height).toBeLessThanOrEqual(page.viewportSize().height);
  await page.screenshot({path:info.outputPath('tutor.png')});
  await page.locator('#tutorAiClear').click();
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(0);
  await send(page,'O que faz a bomba de sódio?');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(1);
  expect(requests[2].history).toHaveLength(0);
  await page.reload();await page.locator('#tutorLauncher').click();
  await expect(page.locator('#tutorAiEnabled')).not.toBeChecked();
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(0);
  expect(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k!=='tutorEFPosition'))).toEqual([]);
  await page.locator('.tutor-close').click();
  const card=page.locator('#cards .card').first();
  await card.locator('[data-open]').click();
  await card.locator('.opts button').first().click();
  await page.locator('#tutorLauncher').click();await page.locator('#tutorAiEnabled').check();
  await send(page,'Explique a alternativa que escolhi.');
  await expect(page.locator('.tutor-ai-answer')).toHaveCount(1);
  expect(requests[3].question).toEqual({index:0,choice:0});
});
test('quiz remains local, chosen answer accompanies explanation; quota fallback',async({page})=>{
  const requests=[];
  await page.route('**/api/tutor',r=>{requests.push(r.request().postDataJSON());return r.fulfill({status:429,json:{error:'limit'}});});
  await open(page);
  await page.locator('.tutor-close').click();
  await page.locator('#cards .card').first().locator('h2').click();
  await page.locator('#tutorLauncher').click();
  await page.locator('[data-prompt="Teste meu entendimento"]').click();
  await page.locator('.tutor-option').first().click();
  expect(requests).toHaveLength(0);
  await send(page,'Por que errei?');
  await expect(page.locator('#tutorMessages')).toContainText('limite de uso');
  expect(requests[0].question.choice).toBe(0);
  await expect(page.locator('.tutor-send')).toBeEnabled();
});
test('cancel releases input; unavailable key retains original tutor',async({page})=>{
  await page.route('**/api/tutor',async r=>{await new Promise(resolve=>setTimeout(resolve,300));await r.fulfill({json:{text:'Não deve aparecer'}}).catch(()=>{});});
  await open(page);await send(page,'Explique a contração muscular');
  await page.locator('#tutorAiCancel').click();
  await expect(page.locator('#tutorMessages')).toContainText('Resposta cancelada');
  await expect(page.locator('.tutor-send')).toBeEnabled();
  await page.unroute('**/api/tutor/status');
  await page.reload();await page.locator('#tutorLauncher').click();
  await expect(page.locator('#tutorAiEnabled')).toBeDisabled();
  await expect(page.locator('#tutorAiNotice')).toContainText('ainda não disponível');
});
for(const course of ['ef','fisio']) test(`Moodle ${course} iframe: shared API, context, clearing, links and no saved conversation`,async({page})=>{
  const requests=[];
  await page.route('**/api/tutor/status',r=>r.fulfill({json:{enabled:true}}));
  await page.route('**/api/tutor',r=>{requests.push(r.request().postDataJSON());return r.fulfill({json:{text:'Resposta simulada: <b>texto seguro</b>'}});});
  await page.goto(base+'/tutor-ef.html');
  await page.setContent(`<iframe title="Tutor Moodle" src="${base}/tutor-moodle.html${course==='fisio'?'?percurso=fisioterapia':''}" style="border:0;width:100%;height:300px"></iframe>`);
  const frame=page.frameLocator('iframe');
  await expect(frame.locator('.head span')).toContainText(course==='fisio'?'Fisioterapia':'Educação Física');
  await frame.locator('[data-action="simuladores"]').click();
  const actual=await frame.locator('a.link').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href')));
  const {loadCatalog}=require('../../server/catalog.cjs');
  const catalog=loadCatalog(require('node:path').resolve(__dirname,'../..'));
  expect(actual).toEqual(catalog[course].map(m=>'https://drmarionascimento.github.io/fisiologia-interativa/'+m.href+(course==='fisio'?'?percurso=fisioterapia':'')));
  await frame.locator('#aiEnabled').check();
  await frame.locator('#input').fill('Por que o sódio entra na célula?');await frame.locator('.send').click();
  await expect(frame.locator('.ai-response')).toContainText('<b>texto seguro</b>');
  await expect(frame.locator('.ai-response b')).toHaveCount(0);
  await frame.locator('#input').fill('Explique com outra analogia');await frame.locator('.send').click();
  await expect(frame.locator('.ai-response')).toHaveCount(2);
  expect(requests[1].history).toHaveLength(2);expect(requests[0].course).toBe(course);
  await frame.locator('[data-action="mapas"]').click();
  await expect(frame.locator('a.link').first()).toHaveAttribute('href',/^https:\/\/drmarionascimento.github.io/);
  expect(requests).toHaveLength(2);
  await frame.locator('#aiClear').click();
  await frame.locator('#input').fill('Explique o potencial de ação');await frame.locator('.send').click();
  await expect(frame.locator('.ai-response')).toHaveCount(2);
  expect(requests[2].history).toHaveLength(0);
  await page.locator('iframe').evaluate(el=>el.contentWindow.location.reload());
  await expect(frame.locator('#aiEnabled')).not.toBeChecked();
  await expect(frame.locator('.ai-response')).toHaveCount(0);
});
